# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='devkor_logo_mini.png', upload_to='media'),
        ),
    ]
