# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190219_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Activity', 'Activity')], default='Announcement', max_length=50),
        ),
    ]
