# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190220_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='adpost',
        ),
        migrations.AddField(
            model_name='adpost',
            name='category',
            field=models.TextField(choices=[('Select Category', 'Select Category'), ('Portfolio', 'Portfolio'), ('Seminar', 'Seminar')], default='Select Category'),
        ),
        migrations.AddField(
            model_name='adpost',
            name='file',
            field=models.FileField(default=None, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
