# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190307_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='images',
            name='adpost',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=None, upload_to='file'),
        ),
        migrations.DeleteModel(
            name='AdPost',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
