# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20190308_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(default='devkor_logo_mini.png', upload_to='thumb')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default=None, upload_to='file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(default='devkor_logo_mini.png', upload_to='thumb')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default=None, upload_to='file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(default='devkor_logo_mini.png', upload_to='thumb')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default=None, upload_to='file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
